# Generated by Django 2.1.7 on 2019-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='send_from',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
