# Generated by Django 2.1.7 on 2019-03-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiManagement', '0003_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
