# Generated by Django 2.0.4 on 2019-02-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_route_route_flights_per_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_flight_volume',
            new_name='route_flights_per_day',
        ),
    ]
