# Generated by Django 2.0.4 on 2019-02-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=30)),
                ('airline_id', models.CharField(max_length=3)),
                ('airline_ontime_departure_rank', models.PositiveSmallIntegerField()),
                ('airline_ontime_arrival_rank', models.PositiveSmallIntegerField()),
                ('airline_arrival_delay', models.SmallIntegerField()),
                ('airline_departure_delay', models.SmallIntegerField()),
                ('airline_flights_per_day', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=30)),
                ('airport_id', models.CharField(max_length=3)),
                ('airport_city', models.CharField(max_length=30)),
                ('airport_state', models.CharField(max_length=2)),
                ('airport_ontime_departure_rank', models.PositiveSmallIntegerField()),
                ('airport_ontime_arrival_rank', models.PositiveSmallIntegerField()),
                ('airport_arrival_delay', models.SmallIntegerField()),
                ('airport_departure_delay', models.SmallIntegerField()),
                ('airport_flights_per_day', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=30)),
                ('route_time', models.PositiveSmallIntegerField()),
                ('route_flight_volume', models.PositiveSmallIntegerField()),
                ('route_flights_per_day', models.PositiveSmallIntegerField()),
                ('route_airlines', models.ManyToManyField(to='api.Airline')),
                ('route_destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='api.Airport')),
                ('route_origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport', to='api.Airport')),
            ],
        ),
    ]
