# Generated by Django 2.1.7 on 2019-02-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('airline_name', models.CharField(max_length=30)),
                ('airline_id', models.CharField(max_length=3)),
                ('airline_percent_ontime_arrival', models.PositiveSmallIntegerField(null=True)),
                ('airline_flights_per_year', models.PositiveIntegerField(null=True)),
                ('airline_departure_delay', models.SmallIntegerField(null=True)),
                ('airline_arrival_delay', models.SmallIntegerField(null=True)),
                ('airline_ontime_departure_rank', models.PositiveSmallIntegerField(null=True)),
                ('airline_ontime_arrival_rank', models.PositiveSmallIntegerField(null=True)),
                ('airline_flight_volume_rank', models.PositiveSmallIntegerField(null=True)),
                ('database_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_name', models.CharField(max_length=30)),
                ('airport_id', models.CharField(max_length=3)),
                ('airport_city', models.CharField(max_length=30)),
                ('airport_state', models.CharField(max_length=2)),
                ('airport_percent_ontime_departure', models.PositiveSmallIntegerField(null=True)),
                ('airport_taxi_in_time', models.SmallIntegerField(null=True)),
                ('airport_taxi_out_time', models.SmallIntegerField(null=True)),
                ('airport_departures_per_year', models.PositiveIntegerField(null=True)),
                ('airport_arrivals_per_year', models.PositiveIntegerField(null=True)),
                ('airport_departure_delay', models.SmallIntegerField(null=True)),
                ('airport_flight_volume_rank', models.PositiveSmallIntegerField(null=True)),
                ('airport_ontime_departure_rank', models.PositiveSmallIntegerField(null=True)),
                ('database_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_airlines', models.ManyToManyField(blank=True, to='api.Airline')),
                ('airport_destinations', models.ManyToManyField(blank=True, to='api.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_name', models.CharField(max_length=30)),
                ('route_time', models.PositiveSmallIntegerField(null=True)),
                ('route_flights_per_year', models.PositiveIntegerField(null=True)),
                ('route_flight_volume_rank', models.PositiveSmallIntegerField(null=True)),
                ('database_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_airlines', models.ManyToManyField(to='api.Airline')),
                ('route_destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='api.Airport')),
                ('route_origin_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_airport', to='api.Airport')),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='airline_destinations',
            field=models.ManyToManyField(blank=True, to='api.Airport'),
        ),
    ]
