# Generated by Django 2.1.7 on 2019-02-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline',
            old_name='database_id',
            new_name='airline_database_id',
        ),
        migrations.AddField(
            model_name='airline',
            name='airline_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
