# Generated by Django 2.1.7 on 2019-02-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190216_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_name',
            field=models.CharField(max_length=60),
        ),
    ]
