# Generated by Django 2.1.7 on 2019-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190212_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
