# Generated by Django 2.1.7 on 2019-03-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190320_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightnumber',
            name='flight_number_unique',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
